### ISSUE TITLE
Add basic support for DataNucleus

### ISSUE THREAD

**Issue by beikov** [Blazebit/blaze-persistence#111]
I already have some code prepared but am still missing some essentials. To be more specific, the dynamic registration of sql methods is still missing.

**Comment by beikov** [comment]
So I got the core testsuite kind of working now. I saw that the tests uncovered some bugs of DataNucleus but I will stop with that integration for now.
The dynamic registration and retrieval of registered sql methods is still missing.

**Comment by andyjefferson** [comment]
Not got time to run your testsuite, but I have some observation(s) on "core/testsuite" package "com/blazebit/persistence/entity", and in particular the Project-ProjectLeader model classes.

1. LargeProject/SmallProject have override of getLeader() to change the signature of the method, when you have generics in the superclass(!) - I presume these overrides were added for some other JPA impl deficiency. DN works fine when these unnecessary overrides are removed (at least on what I tested it for).

2. SeniorProjectLeader/JuniorProjectLeader have override of getLeadedProjects/setLeadedProjects to change the targetEntity and signatures (!). Again unnecessary with generics in the superclass, so assumed to be for some other JPA impl deficiency. DN works fine when these unnecessary overrides are removed (at least on what I tested it for).

3. All models seem to use PROPERTY access type, whilst the majority of JPA users I know would use FIELD from a point of view of what is more convenient (i.e not taking into account where a JPA impl doesn't work well with one or the other). Maybe this is for Hibernate compatibility? but DN is fully tested on FIELD access type (as well as PROPERTY access type *where no overriding is being performed*) and would present a fairer reflection by including some FIELD access.

4. Please raise issues in DN JIRA (with a way of reproducing) rather than hacking some change in your model classes; isn't the aim here for all JPA implementation to handle everything in a predictable way? and if we don't know about things people find, we can't "fix" them

Use of DN nightly build "4.1.0-m3-SNAPSHOT" is the recommended one to use (datanucleus-core, datanucleus-api-jpa and datanucleus-rdbms).
This includes Calendar fix for persisting as DATE or TIME, and corrected check for superclass setters on persistent properties). This version also includes an enhancement fix so that even with the strange override in 2) above it still works for those particular model classes. 
I've not looked at working around the override in 1) above since they basically shouldn't be there and there are higher importance things to do (when fixing the model would remove that problem).

**Comment by beikov** [comment]
1. The override of ```getLeader()``` was necessary because of the ```getProject()``` override in the ProjectLeader classes. Removing them makes the ```getLeader()``` unnecessary.
2. Removed that. Not sure why I added it in the first place. I guess I tried to reproduce a production problem and this was what I ended up with. Anyways, no JPA providers seems to need that override. Removing it also resolves issue 1. which is great. Thanks for mentioning!
3. The simple reason to why I picked property access is because I am used to it. Hibernate works well with field access too if I use the enhancer. I can't speak for eclipselink but I certainly didn't do this for compatibility reasons.
4. Will do that in the future, but as I told you, I hadn't had much time to work on datanucleus integration and the last time working on it I stopped somewhere in the middle of the process of digging into the issues.

**Comment by andyjefferson** [comment]
FYI Using current DN 4.1.0-m5-SNAPSHOT I get your testsuite now giving 6 failures, 74 errors (as opposed to ~200 with 4.1.0-m3). The remainder *seem* to involve some tests for things that are not part of JPA (comparisons between inconsistent expression types, TemporalExpression+integer, use of fields that are not present in a candidate class but are in one subclass) or requiring understanding of the inner workings of your codebase to know where is the problem (the failures *seem* to be that the tests need updating in terms of expectation as opposed to anything specific to DN usage).

**Comment by beikov** [comment]
Thanks Andy!
I will take a look at the rest of the failures when I can spare some time, but right now I am really busy. I will definitely get back to you as soon as I analyzed the rest of the errors in form of JIRA issues ;)

**Comment by beikov** [comment]
Getting closer to a stable version. 4.1.3-SNAPSHOT mostly runs through the test suite! I created JIRA issues for the last outstanding problems.

**Comment by andyjefferson** [comment]
Just ran your tests with your latest code using DN 4.1.5-SNAPSHOT and 5.0.0.M1-SNAPSHOT using h2 and both pass 100%. Congratulations. 
Maybe this issue is complete?

**Comment by beikov** [comment]
As soon as you release 4.1.5 I will close this.

**Comment by andyjefferson** [comment]
FYI datanucleus-rdbms 4.1.5 is now released (in Maven central shortly); other DN plugins remain at 4.1.4 since nothing changed there.

NB, when running with sqlite, I'd suggest using a fixed file (i.e jdbc:sqlite:test.db) rather than memory due to SQLite's in-memory mode seemingly being limited to a single connection (the JDBC driver perhaps). Also note that the SQLite JDBC driver has several bugs, one of which I fixed in https://github.com/andyjefferson/sqlite-jdbc

**Comment by beikov** [comment]
I just switched to the release and everything seems fine. I'll have to wait for sqlite though since I need a maven repo that contains the artifact. Would be very grateful if you notified me when that fix is released!

**Comment by andyjefferson** [comment]
Ok, waiting on sqlite-jdbc to merge it, will let you know.
PS at this line https://github.com/Blazebit/blaze-persistence/blob/master/pom.xml#L106 you need the version to be 5.0.0-m1-SNAPSHOT

**Comment by beikov** [comment]
Ah thanks for the pointer!
