### ISSUE TITLE
Annotation `@JsonIgnore` is not respected in an abstract view class (and interface) correctly

### ISSUE THREAD

**Issue by ahofmeister** [Blazebit/blaze-persistence#1132]
### Description
I am trying to build a view, that is only relevant to search recipes. It fetches additional properties and entities, that are only for internal calculation and there is no need to expose them. For that I added `@JsonIgnore` to that methods.
In the next example, I do not want to expose the quantity of an ingredient, but want to calculate nutrtions with it. 
1 recipe has 2 (quantity) bananas.
```
  @JsonIgnore
  abstract double getQuantity();

```
I therefor put the annotation to ignore the value in the outcoming JSON. 

### Expected behavior
I am expecting, that every(!) property with `@JsonIgnore` annotated does not get exposed into the final JSON.

### Actual behavior

`@JsonIgnore` does not get respected in any way. It gets simple ignored (from my point of view at least)

### Steps to reproduce
As discussed in Slack with @beikov here is a reproducer: https://github.com/ahofmeister/blaze-mapping-reproducer

### Environment
Version: 1.5.0-SNAPSHOT
Quarkus: 1.6.0.FINAL

**Comment by Mobe91** [comment]
I looked at the producer and found that this issue is invalid.

The observed inclusion of `@JsonIgnore`d properties is caused by Eclipse Yasson being used for response body serialization instead of Jackson. Note that `@JsonIgnore` is a Jackson proprietary annotation and is thus only respected if Jackson is used for serialization. Alternatively, you can use `@Transient` which should be respected by both Jackson and Yasson.

I did not investigate the exact reason why Yasson is being used over Jackson. Both are on the classpath and the order of choice may be incidental.

To fix the reproducer, just remove
```
<dependency>
	<groupId>io.quarkus</groupId>
	<artifactId>quarkus-jsonp</artifactId>
</dependency>
<dependency>
	<groupId>io.quarkus</groupId>
	<artifactId>quarkus-resteasy-jsonb</artifactId>
</dependency>
```
from the dependencies as they are not needed and lead to the described provider race between Jackson and Yasson. Also, a `@JsonIgnore` is missing on the `jsonIgnorePackage` property of `org.acme.business.food.IngredientView`.
