### ISSUE TITLE
Entity mapping not working as expected for non-PK referencedColumnName in JoinColumn

### ISSUE THREAD

**Issue by cgraefe** [Blazebit/blaze-persistence#1385]
### Description

In an entity, I have a `@ManyToOne` mapping with a non-PK referencedColumnName and I'm trying to map the target entity into an entity view. Here is an attempt to simplify the setup:

```
@Entity
public class Cat {
    @Id
    private Long id;
    private String name;
    @ManyToOne
    @JoinColumn(referencedColumnName = "code")
    private CatFood favoriteFood;
}

```

```
@Entity
public class CatFood extends AbstractBaseEntity implements Serializable
{
    @Id
    private Long id;
    @Column(nullable = false, unique = true)
    private Long code;
    private String brand;
}
```

```
@EntityView(Cat.class)
public interface CatView
{
    @IdMapping
    Long getId();
    String getName();
    @Mapping("favoriteFood")
    CatFood getFavoriteFood();   
}
```
```

        ID NAME         FAVORITEFOOD_CODE
---------- ------------ -----------------
         1 Lucy           23
         2 Tom             1
         3 Kitty                                                                               


        ID BRAND        CODE
---------- ------------ ----------
         1 Whiskas           23
         2 Purina             1

```

### Expected behavior

When the entity is queried directly, the favorite food should be loaded:
```
Cat cat = cbf.create(em, Cat.class).where("id").eq(2L).getSingleResult();
assertThat(cat.getFavoriteFood(), is(not(nullValue())));
assertThat(cat.getFavoriteFood().getBrand(), is("Purina"));
```

When the entity view is queried, the favorite food should also be loaded:
```
CriteriaBuilder<Cat> cb = cbf.create(em, Cat.class).where("id").eq(2L);
CriteriaBuilder<CatView> viewBuilder = evm.applySetting(EntityViewSetting.create(CatView.class), cb);
CatView catView = viewBuilder.getSingleResult();
assertThat(catView .getFavoriteFood(), is(not(nullValue())));
assertThat(catView .getFavoriteFood().getBrand(), is("Purina"));
```

### Actual behavior
When querying the Cat entity directly, the behavior is as expected. For the catView though, getFavoriteFood() returns null. 

Worse, in my original and much more complex setup the method corresponding to getFavoriteFood() in this example returns the wrong entity if the "food code" in the FK column matches another row with an "id" of the same value. Unfortunately, I couldn't reproduce this exact behavior with the simplified setup.

### Environment
Version:            1.6.3
JPA-Provider:    Hibernate 5.5.7.Final
DBMS:               Oracle
Application Server: Apache Tomcat, Spring Framework

**Comment by beikov** [comment]
Can you try mapping this to a view again just to rule out some fundamental issue with your mapping?

```
Mapping("favoriteFood") CatFoodView getFavoriteFood();
```

**Comment by cgraefe** [comment]
You mean I should try and map the favorite food as another view instead of an entity, like this?

```
@EntityView(CatFood.class)
public interface CatFoodView
{
    @IdMapping
    Long getId();
    String getBrand();
}

@EntityView(Cat.class)
public interface CatView
{
    @IdMapping
    Long getId();
    String getName();
    @Mapping("favoriteFood")
    CatFoodView getFavoriteFood();
}

```

I just tried that and without changing anything else, `catView.getFavoriteFood()` now returns the expected view instance instead of null.

**Comment by beikov** [comment]
Not sure if it is this issue, but I think you are running into https://hibernate.atlassian.net/browse/HHH-12885 which is a pretty old Hibernate bug that we never came around to fix properly. I would recommend you to use entity views all the way anyway to avoid surprises with missing/broken equals/hashCode implementations of the JPA model classes. Blaze-Persistence Entity-Views heavily relies on equals/hashCode to be implemented properly for all attribute types within a view to be able to eliminate duplicates in certain situations. The default implementations of the generated entity view types are known to be safe, so that's not going to be a problem for you if you use entity views everywhere :)

>Worse, in my original and much more complex setup the method corresponding to getFavoriteFood() in this example returns the wrong entity if the "food code" in the FK column matches another row with an "id" of the same value. Unfortunately, I couldn't reproduce this exact behavior with the simplified setup.

Nonetheless I would like to analyze and fix this issue if possible. Do you think you could share an excerpt of your real model through Slack or maybe it is using a `OneToOne(mappedBy)` and the issue I posted really is the reason for the null?

**Comment by cgraefe** [comment]
That Hibernate issue looks like it could be related to this, although I'm using `ManyToOne` here and not `OneToOne`.

Also, you a right of course, there are custom equals/hashCode implementations involved that I've omitted above. Blaze Persistences doesn't even allow entities without those to be mapped into entity views if I noticed correctly. I have quickly put together a minimal but complete project that includes the implementation for those methods and that reproduces the issue with the simplified data model described above. For sake of brevity, I'm using Java SE and H2 this time which doesn't seem to change the behavior:

https://github.com/cgraefe/BlazePersistenceTest

Sharing excerpts of the real model is much harder to do. It is quite extensive and complex and I would first need to find out how much of it and which parts I'd have to share in order to still reproduce the issue.

In the meantime, I will follow your advice to create and map additional entity views. While that might be preferable anyway, it still kinda feels like a work-around, though.

**Comment by beikov** [comment]
Thanks for the reproducer, I'll take a look this weekend.

>While that might be preferable anyway, it still kinda feels like a work-around, though.

Usually, it works fine to use entities as long as the types have sane equals/hashCode implementations. There are just some edge cases related to Hibernate issues like I mentioned. Ultimately, it will be better to use entity views all the way though because you can then fully control what is fetched and how, which entities not necessarily allow in all cases.

**Comment by cgraefe** [comment]
Thanks again for your help and effort!

> Ultimately, it will be better to use entity views all the way though because you can then fully control what is fetched and how, which entities not necessarily allow in all cases.

Generally, I agree! In my particular case, I am using Blaze Persistence to improve a large existing code base with some parts dating back more than 10 years. Being able to (at least temporarily) map entities into views is a nice feature that allows for a more gradual refactoring, imho.

**Comment by beikov** [comment]
Hey, sorry to say that, but I debugged a bit and found out that you are in fact hitting https://hibernate.atlassian.net/browse/HHH-12885 or something very similar at least. It seems the problem is that it is impossible to load a non-pk key joined association via HQL. So the best way to avoid this really is to make use of entity views all the way.

I can assure you though, that this won't be a problem with Hibernate 6.0 anymore as soon as that is out of the door. Maybe I even have time to backport some fixes to 5.x after the Hibernate 6.0 release.

**Comment by cgraefe** [comment]
Good to know, at least. Thanks for looking into this!
