### ISSUE TITLE
App cannot start

### ISSUE THREAD

**Issue by H-Lo** [Blazebit/blaze-persistence#1440]
Hi!
Please can you check this one?
It's not Blazebit bug, but Hibernate is ignoring this issue.
https://hibernate.atlassian.net/browse/HHH-15004
Thanks!

**Comment by beikov** [comment]
Thanks for the ping. I wasn't aware that you were using Blaze-Persistence 😄 
Like I wrote on the Hibernate issue, you seeing this error because of an unfortunate SPI change, which requires that you switch to the new integration module as pointed out in https://persistence.blazebit.com/news/2022/blaze-persistence-1.6.5-release.html
