### ISSUE TITLE
Respect common annotations on EntityViews for GraphQL type generations

### ISSUE THREAD

**Issue by EugenMayer** [Blazebit/blaze-persistence#1488]
We would like to improve the generated types for GraphQL so that one can use (more) of the common annotations on the `EntityViews` to let the type-generation understand, what should be done (like the annotations that are already respected to rename fields).

The aspects we are implementing are
- `javax.validation.constraints.NotNull` - respect if a field should not be nullable, even though the hibernate entity might suggest / reflect it. Just to override that.
- `com.fasterxml.jackson.annotation.JsonIgnore` - respect if a field is marked to be ignored (using thee usual jackson annotation)

**Comment by beikov** [comment]
After some thinking, I decided that I'd rather create custom annotations and also integrate with the annotations from the different GraphQL annotation providers for non-null and ignoring, as not every runtime uses Jackson.

For not-null, I will add support for the various non-null annotations though because a language level "non-null" annotation can be seen as a "strong" guarantee that this will really always be not null. A `@JacksonIgnore` might not mean that a field is ignored by every runtime and when using a view in different runtimes (WebMvc and GraphQL), one might want to differentiate if a field should be ignored in one runtime or another.

**Comment by EugenMayer** [comment]
I can follow you on that. 

But AFAIU you will support javax.validation.constraints.NotNull in addition, right?

**Comment by EugenMayer** [comment]
@beikov AFAIR you implemented this now, right? (i assume this issue can be closed - IMHO)
