### ISSUE TITLE
DataNucleus handling extensions is missing META-INF/MANIFEST.MF

### ISSUE THREAD

**Issue by andyjefferson** [Blazebit/blaze-persistence#217]
If specifying DataNucleus extensions (via plugin.xml), as DN docs mention, you also need to supply META-INF/MANIFEST.MF. See https://github.com/Blazebit/blaze-persistence/tree/master/integration/datanucleus/src/main/resources

Fixing this would avoid pages of log messages down the screen.

**Comment by beikov** [comment]
Maybe that only happens in your test environment because the maven build should actually generate the manifest(https://github.com/Blazebit/blaze-persistence/blob/master/integration/datanucleus/pom.xml#L127). I could add a static file which i suppose gets overwritten by the maven build then if that helps.

**Comment by andyjefferson** [comment]
I do "mvn clean install" then "mvn clean test -Pdatanucleus-5,h2" from the top level. No idea if that is an incorrect way to invoke it

**Comment by beikov** [comment]
Ahh that explains it. If you do clean and test it won't get to the packaging phase which results in not generating the manifest because the jar plugin does not run. I'll add a base file that should suffice for this case.
