### ISSUE TITLE
Improve documentation on predicate reuse and builders usage

### ISSUE THREAD

**Issue by weblogichub** [Blazebit/blaze-persistence#350]
Chapter 5 say about reuse of predicates, but not contain any example of  independently created and reused predicate(a la QueryDSL Predicate in spring data repositories). Need documentation on RestrictionBuilder(and other builders) usage with CriteriaBuilder.

**Comment by beikov** [comment]
The reuse part is about making use of the same API for building restrictions throughout all clauses rather than reusing _externally_ defined predicates. Would you mind explaining what you don't understand or what needs better explaining?

There are tons of examples for all kinds of predicates(EQ, LIKE, etc.) that are buildable with the `RestrictionBuilder` API, so I am not sure what you mean.

**Comment by weblogichub** [comment]
I mean externally defined predicates. Like QueryDslPredicateExecutor methods params in spring data repositories.

**Comment by beikov** [comment]
There is no support for external predicates right now, because we have no standalone API for predicate construction but only have a way to create predicates fluently when using the `CriteriaBuilder` API.

I would have suggested to try the [JPA Specifications](https://spring.io/blog/2011/04/26/advanced-spring-data-jpa-specifications-and-querydsl/) feature for doing this, but I just tried it out and it doesn't work.

The spring-data-jpa integration is still in the early stages and there are probably many unexpected limitations. I'll create some issues for the features that come to my mind.

Apart from these limitations and the currently non-existent documentation for the spring-data integration, have you tried using entity views? Entity views have a concept called [`attribute filters`](https://persistence.blazebit.com/documentation/entity-view/manual/en_US/index.html#filter-and-sorter-api) which allows to define filters on the target projection that can be enable selectively. This will help with reducing the boilerplate if you want to work with read only DTOs. For entity related queries, you'd unfortunately have to wait until we fix this.

**Comment by beikov** [comment]
Here is the issue for the [Spring-Data JPA Specifications](https://github.com/Blazebit/blaze-persistence/issues/351) and another one for using entity view settings in [Spring-Data JPA Repositories](https://github.com/Blazebit/blaze-persistence/issues/325)

**Comment by beikov** [comment]
Are the JPA specifications a solution to your problem/question? If so I'd like to close this issue if there are no further questions regarding reusability. I could also try to reword the documentation if you want.
