### ISSUE TITLE
Add more temporal related functions

### ISSUE THREAD

**Issue by beikov** [Blazebit/blaze-persistence#380]
We are still lacking some date extract functions
* `microsecond`
* `millisecond`
* `week`
* `quarter`
* `dow` - day of week 0 (Sunday) - 6 (Saturday)
* `doy` - day of year (extract(day from ? - trunc_year(?)))

Also need some more diff functions
* `epoch_diff`
* `microsecond_diff`
* `week_diff`
* `quarter_diff`

Also add tests to make sure the diffing functions produce correct results i.e. a day_diff between _01-01-2001_ and _01-01-2002_ produces 365/366 days.

Something that we currently don't have but would be quite useful for grouping is a date truncation i.e. `trunc_hour(...)` should truncate off the minutes, seconds and fractional part.

Add support for the following functions
* `trunc_microseconds`
* `trunc_milliseconds`
* `trunc_second`
* `trunc_minute`
* `trunc_hour`
* `trunc_day`
* `trunc_week`
* `trunc_month`
* `trunc_quarter`
* `trunc_year`

PostgreSQL has these functions builtin and should serve as reference for how to implement the functions: https://www.postgresql.org/docs/9.4/static/functions-datetime.html

**Comment by Mobe91** [comment]
`epoch_diff` can be easily done using `epoch`...

**Comment by beikov** [comment]
The thing is, that using `epoch() - epoch()` might not be as efficient as what we can do with a custom epoch diff function

**Comment by Mobe91** [comment]
For most databases there is probably no better way to do it.

**Comment by beikov** [comment]
DBMS that support epoch extraction through a single function call are the exception to this obviously. But for some DBMS we have to calculate the epoch from various diffs(oracle) and we could optimize this for these DBMS.

**Comment by JWGmeligMeyling** [comment]
Some date parts include others: i.e. milliseconds contains seconds & microseconds contains milliseconds (and thus seconds too). I imagine this to be different across various databases too. Return whatever the database returns or should we attempt to smoothen this out?

Considering the existence of issue https://github.com/Blazebit/blaze-persistence/issues/493 I suggest that if smoothened out at all, we change the usual DBMS behaviour for the date extract functions.

Which effectively means that milliseconds and nanoseconds should both be wrapped in a modulo 1000 operation.

**Comment by beikov** [comment]
> Return whatever the database returns or should we attempt to smoothen this out?
IMO we should smoothen this out.
> we rather change the usual DBMS behaviour for the date extract functions.
Yeah, extract only the actual parts. The functions should behave the same on all DBMS.

**Comment by JWGmeligMeyling** [comment]
Day of week and week in year are locale specific, and return different results across different databases with different configurations. It's going to take a disproportional amount of time to test which of all databases we support actually allow to set a locale based definition of weeks in the application. An amount that IMO doesn't really make sense to invest: an application dependent on those values is better of implementing their own interpretation of weeks rather than relying on the databases definition anyway.

For DAY_OF_WEEK and WEEK_IN_YEAR we could do either of two things imo:

1. do not provide a function mapping at all, just let the use of the function fail
2. do not really care about the differences between various databases (potentially with a warning reporting the subtle differences)

**Comment by beikov** [comment]
This seems to be dependent on whether the functions implement the ISO standard, not locale dependent and I would prefer to follow the ISO standard by default.

There is an issue on Oracle: https://travis-ci.org/JWGmeligMeyling/blaze-persistence/jobs/572446771
And an issue on MSSQL: https://travis-ci.org/JWGmeligMeyling/blaze-persistence/jobs/572446769#L1730

Interstingly, PostgreSQL by default implements the ISO standard and correctly handles that the 1. January 2000 was still in the last week of the year 1999 which results in 52 rather than 1: https://travis-ci.org/JWGmeligMeyling/blaze-persistence/jobs/572446768#L1731
Also see the comments for a "solution": https://stackoverflow.com/questions/34050103/extract-week-number-from-date-postgres

IMO we should provide database implementation independent solutions, after all, that's the whole point of these functions. Providing standard functionality that can be relied upon regardless of the underlying database implementation. If one wants the native functionality, that person can introduce simple wrapper functions for the native functions.

I would opt for following the ISO standard by default and maybe provide another function e.g. `WEEK_IN_YEAR` that returns 1 for the 1. January 2000. Adapting the use of `DAY_OF_WEEK` as a user is easy, one can adapt to the fact that MONDAY is 1 and SUNDAY is 7, but `WEEK_IN_YEAR` and `WEEK` are special as they implement different handling that isn't easy for a user to reproduce. I hope that all DBMS have implementations for the ISO `WEEK`, if they don't, we will have to think about a good implementation.

**Comment by JWGmeligMeyling** [comment]
Because the Java Calendar interface actually returns the wrong WEEK_IN_YEAR, the test passes are actually our failures... Which means that all dialects are failing: DB2, Oracle, MSSQL, MySQL... MySQL pretends to be ISO compatible but is very vague about how to obtain an ISO compatible week. It seems to be [mode 2](https://dev.mysql.com/doc/refman/5.5/en/date-and-time-functions.html#function_week) of the options: `SELECT WEEK('2000-01-01',2)`. I have no clue how to obtain the ISO week in DB2, Oracle, MSSQL or even from the Java Calendar API properly.

The problem is that even with a correct implementation of the week extraction, it will have to be used with a lot of caution because there is no function to obtain the associated year of the week (which is not necessarily the year of the date). We would have to implement a function for that too. It is also plausible that the user never actually intended to use ISO week definitions in the first place. At that point, as a developer, I'd rather truncate dates by the start of the week and group by that. Or create a CTE/generated series with my exact definition of weeks and join that instead.

The way I see it at this point a natural week utility API is something entirely different than a bunch of convenience date extraction methods. It is going to require a lot more research and is going to require a lot more additions (year of week functions, locale specific weeks and configuration) that shouldn't be implemented as a simple date extraction function because it would just confuse users. I suggest to remove the week accessors from the PR.

That leaves us with two more test failures:

1. Oracle fails on a missing right parenthesis. I checked the Oracle specific implementations and have not found the failing expression yet. I am going to split up the test in several test cases to find which one is failing. Hopefully its the WEEK one ;-)
2. MS SQL seems to round the timestamp in some way, as it returns 413 ms rather than 412 ms as set in the timestamp. After splitting up the tests, I'll probably end up ignoring the test for millisecond extraction for MSSQL.

**Comment by beikov** [comment]
According to the following, it should be possible to get the ISO format via the calendar API as well: https://stackoverflow.com/a/20199492/412446

According to the DB2 docs, the ISO week can be retrieved with the `DATE_PART` function: https://www.ibm.com/support/knowledgecenter/en/SSEPGG_11.1.0/com.ibm.db2.luw.sql.ref.doc/doc/r0061971.html

I suppose other DBMS have similar possibilities.

> The problem is that even with a correct implementation of the week extraction, it will have to be used with a lot of caution because there is no function to obtain the associated year of the week (which is not necessarily the year of the date). We would have to implement a function for that too. It is also plausible that the user never actually intended to use ISO week definitions in the first place. At that point, as a developer, I'd rather truncate dates by the start of the week and group by that. Or create a CTE/generated series with my exact definition of weeks and join that instead.

I agree that we should maybe also provide a `year_of_week` function to handle this incoveniences properly.

> The way I see it at this point a natural week utility API is something entirely different than a bunch of convenience date extraction methods. It is going to require a lot more research and is going to require a lot more additions (year of week functions, locale specific weeks and configuration) that shouldn't be implemented as a simple date extraction function because it would just confuse users. I suggest to remove the week accessors from the PR.

The functions should provide database independence and should be clearly specified i.e. ISO week or week of the year, but using them correctly is up to the user. I don't know if there are locale specifics involved here, but the ISO week and week in year functions are standard in all kinds of systems, so IMO this is just an abstraction over the DBMS specifics.

> MS SQL seems to round the timestamp in some way, as it returns 413 ms rather than 412 ms as set in the timestamp. After splitting up the tests, I'll probably end up ignoring the test for millisecond extraction for MSSQL.

That's odd, let's hope we are not doing something wrong here 😅
