### ISSUE TITLE
Allow subtype equality in EntityView equals-hashCode implementation

### ISSUE THREAD

**Issue by Mobe91** [Blazebit/blaze-persistence#430]
At the moment, the equals-hashCode implementation in the generated entity view proxies require type equality which can be hindering in many usage scenarios. Therefore the implementation should be changed to equality in case of compatible subtypes with equal IDs.

**Comment by beikov** [comment]
Now if you have two entity view V1 and V2, where V2 extends V1, calling `V1.equals(V2)` would return **true** but `V2.equals(V1)` would return **false** which kind of breaks the general equals-hashCode contract.

I think a better approach is to test for *entity type* equality. Since both V1 and V2 are views on the entity type E we could determine compatibility by that fact. What do you say?

**Comment by Mobe91** [comment]
True, that's a problem.
Using *entity type* equality sounds good.

**Comment by beikov** [comment]
I'm starting to think that #440 is the more proper solution to the underlying problem.  An explicit conversion would make the intent much clearer. What do you say? Would that be sufficient or are there cases where a conversion would be unpleasant?
If you have hash maps or set, you could work with a value wrapper that implements the equality checking based on what you would like, the entity type and the id, but I'm simply not sure it's such a good idea to always do it like this. Maybe you can convince me? :)

**Comment by beikov** [comment]
Ok, the argument, that entity views are just a fragment of an entity which shouldn't change the identity regarding equals-hashCode convinced me. I will implement that in an upcoming version.
