### ISSUE TITLE
API changes review for Blazebit Persistence Core

### ISSUE THREAD

**Issue by lvc** [Blazebit/blaze-persistence#446]
The review of API changes for the Blazebit Persistence Core library since 1.0.0 version: https://abi-laboratory.pro/java/tracker/timeline/blaze-persistence-core-api/

The report is updated 3 times a week (Mon, Wed, Fri). Hope it will be helpful for users and maintainers of the library.

The report is generated by https://github.com/lvc/japi-tracker and https://github.com/lvc/japi-compliance-checker tools.

Thank you.

![blaze-persistence-core-api-2](https://user-images.githubusercontent.com/1517837/30953674-fdb95a1e-a43d-11e7-9a93-fa1034e2cd9a.png)
![blaze-persistence-core-api-1](https://user-images.githubusercontent.com/1517837/30953675-fddfd0fe-a43d-11e7-9afd-d1f40f20ca91.png)

**Comment by beikov** [comment]
This is a very interesting tool, thank you for doing this! Do you scan Maven releases or the GitHub source? It would be nice to be able to know of incompatibilities before a release or maybe continuously based on the current state.
Is there an option to ignore the "a client class C is not abstract and does not override abstract method" errors? These aren't errors in my opinion because almost all API classes aren't supposed to be implemented by users but just used. How could the types be differentiated?

**Comment by lvc** [comment]
Hi,

> Do you scan Maven releases or the GitHub source?

The tool scans http://central.maven.org/maven2/com/blazebit/blaze-persistence-core-api/.

The tool can check daily/weekly snapshots of a library if you build and share them somewhere. Also you can just release a beta or alpha version and it will appear at the top of the compatibility table.

> Is there an option to ignore the "a client class C is not abstract and does not override abstract method" errors?

Do you mean added abstract methods to interfaces and added super-interfaces for interfaces only? I can disable checking of such rules for the library and make a note in the compatibility table about this.

Thank you.
