### ISSUE TITLE
TupleObjectBuilder.aliases is not initialised properly 

### ISSUE THREAD

**Issue by JWGmeligMeyling** [Blazebit/blaze-persistence#490]
It seems that `TupleObjectBuilder#aliases` is not initialised properly. The code copies the provided values from the `List<SelectInfo> selectInfos` parameter in to an local array, but this is done in the constructor, which is invoked through the constructor of `SelectManager`, at a time when `List<SelectInfo> selectInfos` is still empty. The code is dependent on mutation from outside, but the values are copied on construction. This causes `TupleObjectBuilder$TupleImpl$TupleElementImpl.getAlias()` to fail with an `java.lang.ArrayIndexOutOfBoundsException`.

**Comment by JWGmeligMeyling** [comment]
Suggested solution: 
* Remove `List<SelectInfo> selectInfos` parameter from `TupleObjectBuilder` constructor
* Move `String[] aliases` from `TupleObjectBuilder` to `TupleObjectBuilder.TupleImpl`
* In `TupleObjectBuilder.TupleImpl`, traverse `Map<String, Integer> selectAliasToPositionMap` to fill the local `String[] aliases`.

If this approach is approved, I'll submit a patch.

**Comment by JWGmeligMeyling** [comment]
I am not sure whether the `List<SelectInfo> selectInfos` is kept up to date, if that is the case, an easier solution would be to:
* Store a reference to `selectInfos` without copying it into an array
* Replace uses of `aliases[...]` with `selectInfos.get(...)`.

**Comment by beikov** [comment]
The problem is that the CriteriaBuilder could change after retrieving a result, so there needs to be a copy of the select item aliases and actually, the select alias to position map should also be copied. I was thinking of deferring the instantiation of the `TupleObjectBuilder` until the query is built(a call to `getSelectObjectBuilder` is made), which should fix the issue and even allow for the underlying builder to change after constructing the query without affecting already built queries.
From what I see, it'd also be necessary to store the produced object builder in `com.blazebit.persistence.impl.AbstractCommonQueryBuilder#applyObjectBuilder` into a local variable to avoid creating it twice.
Want to give it a try? 😃

**Comment by JWGmeligMeyling** [comment]
I'll give it a try!
