### ISSUE TITLE
Complex aggregation expressions in CriteriaBuilder sometimes produce a malformed query.

### ISSUE THREAD

**Issue by JWGmeligMeyling** [Blazebit/blaze-persistence#491]
### Description
Complex aggregation expressions in CriteriaBuilder sometimes produce a malformed query.

As part of a larger query I have the expression:

```java
criteriaBuilder.select("AVG(CASE WHEN FUNCTION('date_part', 'hours', cgts.duration) > 0 " +
 "THEN cgls.teacherSalary * -1 / FUNCTION('date_part', 'hours', cgts.duration) " +
 "ELSE NULL END)", "averageTutorSalary")
```

This translates to the JPQL segment:
```
AVG(CASE
     WHEN FUNCTION('date_part','hours',cgts.duration) > 0 THEN (cgls.teacherSalary * -1 / FUNCTION('date_part','hours',cgts.duration))
    ELSE NULL
END) AS averageTeacherSalary,
```

Which translates to the SQL segment:
```
avg(CASE WHEN date_part('hours') AS col_8_0_,
```

Which is completely messed up. Surprising enough: the same aggregation with `SUM` works fine. I think this could very well be a bug in Hibernate itself (given that the JPQL query seems allright).

### Environment

Version:             1.2.0.Alpha3
JPA-Provider:       Hibernate 5.2.12
DBMS:               Postgresql
Application Server:  Wildfly 10

**Comment by JWGmeligMeyling** [comment]
Worked around the issue by defining a function that returns an explicit type, like such:

```java
        metadataBuilder.applySqlFunction("INTERVAL_TO_NUMERIC_HOURS",
            new SQLFunctionTemplate(BigDecimalType.INSTANCE, "EXTRACT(epoch FROM ?1) / 3600"));
```

So this is clearly a problem in Hibernate not being able to figure out the return type of the expression and messing up the query.

**Comment by beikov** [comment]
I'd be interested to know where the problem in Hibernate is exactly. You mentioned a problem with the AVG function for the second time and I think it's worth implementing an automatic workaround within Blaze-Persistence for this. Have you debugged it, is just the return type of the AVG function the problem? Or is the AVG function maybe handled somewhere specially which messes the query up?

**Comment by JWGmeligMeyling** [comment]
I didn't fully debug this issue yet, but wanted to reproduce it to submit an issue to Hibernate nevertheless.  Just didn't get to it yet.

The final expression, using the new function, is:

```
.select("AVG(CASE WHEN FUNCTION('INTERVAL_TO_NUMERIC_HOURS', cgts.duration) >= 1 AND cgls.teacherSalary <> 0 THEN cgls.teacherSalary * -1 / FUNCTION('INTERVAL_TO_NUMERIC_HOURS', cgts.duration) ELSE NULL END)", "averageTeacherSalary")
```

It still calls a function in the case expression and the function still consumes my custom PGInterval type, so that can't be the problem. The only difference in the produced JPQL is that the function has 2 arguments instead of 3 and that the return type is known to be a BigDecimalType. So it must be something related to this. Might have to do something with the custom type for PGInterval anyways, the type determination of the aggregation and sum operator result seems to be relatively basic implementation, which differs across various aggregation types (SUM seems to be the most sophisticated) and in practise it probably differs per dialect.

**Comment by beikov** [comment]
Have you tried what happens when putting parenthesis around the _case when expression_ and/or the conditions/expressions like `AVG((CASE WHEN (FUNCTION('date_part', 'hours', cgts.duration) > 0) THEN (cgls.teacherSalary * -1 / FUNCTION('date_part', 'hours', cgts.duration)) ELSE NULL END))`. Maybe the Hibernate parser messes this up somehow?
The `date_part` function doesn't seem to be registered in the dialect, so I'm not sure what kind of return type it would report.

Also, just wanted to mention you can use one of the built-in functions like e.g. `epoch` to extract the epoch of a timestamp/interval. In case of PostgreSQL it would render `extract(epoch from ?)`. Here is a list of the functions: https://persistence.blazebit.com/documentation/core/manual/en_US/index.html#temporal-extract-functions

**Comment by beikov** [comment]
Also note I created an issue for the temporal extraction of _full temporal units_ here: #493

**Comment by JWGmeligMeyling** [comment]
I will try it with the extra parenthesis. If I remember correctly I initially tried parenthesis around the function invocation, but did not try them around the entire `CASE WHEN` expression.

I see that I missed the extract method in Blaze too. I assumed it would be Postgresql specific and wouldn't work. But these temporal extractions only work on Hibernate supported temporal fields right? Because in this case I am using an `PGInterval`  mapped to a `java.time.Duration` which is Java 8 and not the default / even possible in Hibernate 5 as far as I know.

**Comment by beikov** [comment]
The type of what is passed in to a function isn't checked currently and the java type of arguments aren't particularly relevant here since the output types for these functions are always the same. Most functions work with all types from the perspective blaze-persistence and Hibernate. In the end, the database is will return an SQL error if types are wrong.
