### ISSUE TITLE
Enhancement: make line separator in CTE query string configurable

### ISSUE THREAD

**Issue by jwgmeligmeyling** [Blazebit/blaze-persistence#495]
When using CTE queries, the produced CTE query string contains line separators. When I enable query logging by enabling `hibernate.show_sql` the query spans over multiple log lines. As I am using Logback / Slf4j, each line is prefixed with a timestamp / thread name etc. I therefore can't easily copy the SQL string (for example to inspect it or run an explain query against it). But it potentially has some side effects for monitoring as well (I haven't observed such however).

- Is the new added line separator required for some DB dialects?
- If not, can we make this pretty print behaviour configurable?
- If we do, should / could we reuse the `hibernate.format_sql` property (and possibly any Datanucleus equivalent) or should we ship our own property for this?

**Comment by beikov** [comment]
There is no separator required, it was just done for better readability.
I guess we could reuse the parameters of the JPA providers during construction of the `CriteriaBuilderFactory`

**Comment by JWGmeligMeyling** [comment]
<img width="1491" alt="Screenshot 2019-09-26 at 11 24 10" src="https://user-images.githubusercontent.com/3469492/65676715-ac0c3f00-e050-11e9-9c48-51e4c72d52ab.png">

As you can see, NewRelic for example seems to remove the `\n` leaving no whitespace between the CTE keywords and making it harder to copy/paste the query (i.e. for an `explain analyze`).

However, I've noticed that '\n` characters are added in quite a few places already in both JPQL and generated SQL, and are also verified against in a couple of assertions.

I think the easiest implementation is to use a plain space as seperator instead of '\n' based on the property. Couple of questions:

- Should the property be added to `ConfigurationProperties` and `AbstractQueryConfiguration`? Or just use the `properties` from `CriteriaBuilderConfigurationImpl`?
- How to get hold of a `QueryConfiguration`?
- Do we still want to default the value to the JPA provider formatting style, and if so, how do we do that nicely? (`AbstractQueryConfiguration` currently lacks context)

**Comment by beikov** [comment]
How about simply rendering ` \n` i.e. add a space before the `\n`. Would that help you?
We can of course introduce a property to control this. I suggest we add it to `ConfigurationProperties` and put that into `QueryConfiguration` which is accessible through the `MainQuery` object in almost any context.
We can parse a few well known properties by doing e.g. `if ("true".equals(entityManagerFactory.getProperty("hibernate.format_sql")) { properties.put(ConfigurationProperties.SEPARATE_CTE_WITH_SPACE, true); }` within the `createCriteriaBuilderFactory()` method

**Comment by JWGmeligMeyling** [comment]
I'll give this issue a go. It hasn't really been a show stopper for me in the past two years but I think it would be nice to get it out of the way 😄  and it seems to be a very small fix anyway.

**Comment by JWGmeligMeyling** [comment]
Hmm, lots of SQL generation happens within the dialects and `CustomQuerySpecification` (note that I'm mostly talking about the generated SQL and not necessarily the generated JPQL). Both of these classes currently do not have access to a `QueryConfiguration`, and for the dialects in particular it will be difficult to pass it on. Perhaps changing the default character used is easier, although it would require a lot of test assertions to be updated as well.
