### ISSUE TITLE
View_Root macro does not work properly with FetchStrategy = SELECT

### ISSUE THREAD

**Issue by philippEder** [Blazebit/blaze-persistence#555]
### Description

The base query restricts the query root but the VIEW_ROOT macro for the correlation uses an unrestricted query root.

### Environment

Version:            
JPA-Provider:       
DBMS:               
Application Server:

**Comment by beikov** [comment]
Could you please give me more details on this? Generally, when a VIEW_ROOT is involved, the following happens when using the SELECT strategy.

1. Invoke main query and extract correlationBase
2. Invoke query for correlated entity with a where clause containing the correlation expression and a select item for the correlationBase and another item for the view root id. The results are then matched with the results from the main query by the correlation value and view root id
3. Go to 2. until all results for all correlation values were fetched

An example model would already help a lot

**Comment by beikov** [comment]
As far as I can tell, this was fixed by f78bf07
