### ISSUE TITLE
Allow to convert entities to entity views

### ISSUE THREAD

**Issue by beikov** [Blazebit/blaze-persistence#632]
We already have our conversion API in the `EntityViewManager` which supports conversion between entity view types. When we have a proper JPQL interpreter, it should be possible to implement conversion of entities to entity views.
This is a follow up of https://github.com/Blazebit/blaze-persistence/issues/127

**Comment by danelowe** [comment]
@beikov I'm really intererested in this. Any idea where to start?

**Comment by beikov** [comment]
Hi @danelowe,

it really depends how far you want to go with this. Simple attribute path mappings should be easy to implement as that is what we did for entity view conversion already. The tough part would be to support interpreting JPQL functions.

By where to start, you mean you would like to try to implement this? If so, I guess it would be good to take a look at how the view to view mapping works in `com.blazebit.persistence.view.impl.mapper.ViewMapper`. You would have to loop through the attributes, cast them to `AbstractAttribute<?, ?>` and check if `getMappingType() == BASIC`. Next you'd parse the result of `getMapping()` with `entityViewManager.getService(ExpressionFactory.class).createSimpleExpression()`. Check that the result of that is a `PathExpression` and create an array of `AttributeAccessor` for accessing the state from the entity. During mapping, you invoke all of these and the result should be the value for the attribute. Collect that in an object array like in `ViewMapper` and similarly pass the tuple to the entity view constructor.

**Comment by danelowe** [comment]
Hi @beikov 

I was considering trying to implement this as I figured I'd need to in order to get the functionality. I also thought it might be good for me to try to understand how it works.

I spent half a day trying to grok the codebase, and I'm quite lost with it still. I'm definitely not finding it easy to implement myself. Maybe I'm on the wrong track, or maybe I don't understand what I'm looking at.

I've submitted a draft PR if you'd like to have a look.
