### ISSUE TITLE
Optimize subquery transformation for SIZE() select clauses

### ISSUE THREAD

**Issue by Mobe91** [Blazebit/blaze-persistence#67]
We could use the inverse mapping for creating the COUNT() subqueries. This way we could save a join.

**Comment by beikov** [comment]
I would like to recap what the intention of this issue was since it's very old now.

Right now, we transform SIZE functions into subqueries that do COUNT. When having

    SELECT SIZE(a.collection) FROM A a

it get's transformed to

    SELECT (SELECT COUNT(y) FROM A x LEFT JOIN x.collection y WHERE x.id = a.id) FROM A a

although it could be transformed into

    SELECT (SELECT COUNT(y) FROM B y WHERE y.a.id = a.id) FROM A a

if we know the inverse relation.

According to the JPQL BNF we could also transform it into the following equivalent query

    SELECT (SELECT COUNT(y) FROM a.collection y) FROM A a

which would be even easier.

**Comment by beikov** [comment]
Fixed
